# Generated by Django 5.0.2 on 2024-02-22 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the topic.', max_length=128)),
                ('description', models.TextField(help_text='Description of topic.')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(help_text='Topic creator', on_delete=django.db.models.deletion.CASCADE, related_name='discussionsTopics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment text.', max_length=1024)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(help_text='Comment author', on_delete=django.db.models.deletion.CASCADE, related_name='discussionsComments', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(help_text='The topic this comment is part of', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.topic')),
            ],
        ),
    ]
