# Generated by Django 5.0.2 on 2024-02-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-createdAt',)},
        ),
    ]
