# Generated by Django 4.2.6 on 2023-10-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_owner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
