# Generated by Django 5.0.2 on 2024-02-20 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_owner_slug_alter_tool_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Non-Accessible'), (2, 'Partially Accessible'), (3, 'Mostly Accessible'), (4, 'Highly Accessible'), (5, 'Fully Accessible')]),
        ),
    ]
