# Generated by Django 4.2.6 on 2023-11-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_owner_verified_tool_verified_alter_tool_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='slug',
            field=models.SlugField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(default='', max_length=128),
        ),
    ]
